---
include:
  default:
    - profile::openstack::metric
    - profile::openstack::openrc


# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

profile::base::common::packages:
  'python-openstackclient': {}

profile::openstack::metric::manage_firewall:       true

profile::openstack::openrc::password:     "%{hiera('gnocchi_api_password')}"
profile::openstack::openrc::username:     'gnocchi'
profile::openstack::openrc::project_name: 'services'
